import { ServiceItem } from '@/types';

export const services: ServiceItem[] = [
  {
    slug: 'desfocar-nitidez',
    icon: 'Focus',
    titleKey: 'desfocarNitidez',
    descriptionKey: 'desfocarNitidezDesc',
    category: 'enhancement',
    flowService: 'restauracao',
    accent: 'violet',
  },
  {
    slug: 'redutor-ruido',
    icon: 'AudioLines',
    titleKey: 'redutorRuido',
    descriptionKey: 'redutorRuidoDesc',
    category: 'enhancement',
    flowService: 'restauracao',
    accent: 'blue',
  },
  {
    slug: 'restaurador-fotos-antigas',
    icon: 'Clock',
    titleKey: 'restauradorFotos',
    descriptionKey: 'restauradorFotosDesc',
    category: 'enhancement',
    flowService: 'restauracao',
    accent: 'amber',
  },
  {
    slug: 'ampliador-imagem',
    icon: 'Maximize2',
    titleKey: 'ampliadorImagem',
    descriptionKey: 'ampliadorImagemDesc',
    category: 'enhancement',
    flowService: 'restauracao',
    accent: 'cyan',
  },
  {
    slug: 'corretor-cor',
    icon: 'Palette',
    titleKey: 'corretorCor',
    descriptionKey: 'corretorCorDesc',
    category: 'enhancement',
    flowService: 'estilizacao',
    accent: 'fuchsia',
  },
  {
    slug: 'realcador-facial',
    icon: 'Smile',
    titleKey: 'realcadorFacial',
    descriptionKey: 'realcadorFacialDesc',
    category: 'enhancement',
    flowService: 'restauracao',
    accent: 'rose',
  },
  {
    slug: 'aprimorador-fundo',
    icon: 'Mountain',
    titleKey: 'aprimoradorFundo',
    descriptionKey: 'aprimoradorFundoDesc',
    category: 'enhancement',
    flowService: 'limpeza',
    accent: 'emerald',
  },
  {
    slug: 'melhorador-baixa-qualidade',
    icon: 'Sparkles',
    titleKey: 'melhoradorBaixaQualidade',
    descriptionKey: 'melhoradorBaixaQualidadeDesc',
    category: 'enhancement',
    flowService: 'restauracao',
    accent: 'violet',
  },
  {
    slug: 'aprimorador-video',
    icon: 'Video',
    titleKey: 'aprimoradorVideo',
    descriptionKey: 'aprimoradorVideoDesc',
    category: 'video',
    flowService: 'video',
    accent: 'blue',
  },
  {
    slug: 'adicionar-pessoas',
    icon: 'UserPlus',
    titleKey: 'adicionarPessoas',
    descriptionKey: 'adicionarPessoasDesc',
    category: 'generative',
    flowService: 'composicao',
    accent: 'emerald',
  },
  {
    slug: 'remover-objetos',
    icon: 'Eraser',
    titleKey: 'removerObjetos',
    descriptionKey: 'removerObjetosDesc',
    category: 'generative',
    flowService: 'limpeza',
    accent: 'rose',
  },
  {
    slug: 'filtros-efeitos',
    icon: 'Wand2',
    titleKey: 'filtrosEfeitos',
    descriptionKey: 'filtrosEfeitosDesc',
    category: 'generative',
    flowService: 'estilizacao',
    accent: 'fuchsia',
  },
];

export function getServiceBySlug(slug: string) {
  return services.find((s) => s.slug === slug);
}
